[project]
name = "hass-mcintosh"
requires-python = ">=3.13"

[tool.ruff]
line-length = 100
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
ignore = [
    "F405",  # * imports
]

[tool.ruff.format]
quote-style = "single"
